# Generated by Django 5.0.1 on 2024-03-06 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.DeleteModel(
            name='ticket',
        ),
        migrations.AlterField(
            model_name='registro',
            name='devoluciones',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado_liquidaciones',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado_sistemas',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_liquidaciones',
            field=models.TextField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_sistemas',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='registro',
            name='observaciones',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='registro',
            name='operador_liquidaciones',
            field=models.CharField(default='enzofuentes', max_length=100),
        ),
        migrations.AlterField(
            model_name='registro',
            name='operador_sistemas',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
