# Generated by Django 5.0.3 on 2024-03-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_usuario_delete_prueba_delete_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='operador_liquidaciones',
            field=models.CharField(default='Administrator', max_length=100),
        ),
    ]
