# Generated by Django 5.0.3 on 2024-03-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_registro_operador_liquidaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='operador_liquidaciones',
            field=models.CharField(max_length=100),
        ),
    ]
