# Generated by Django 5.0.3 on 2024-03-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_registro_operador_liquidaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='operador_liquidaciones',
            new_name='usuario',
        ),
    ]
