# Generated by Django 5.0.3 on 2024-03-08 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_registro_devoluciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_liquidaciones',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
