# Generated by Django 5.0.1 on 2024-03-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_rename_id_registro_ticket_id_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
