# Generated by Django 5.0.3 on 2024-03-15 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_delete_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistemas',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='nombre',
            new_name='agente_nombre',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='estado_liquidaciones',
            new_name='estado_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fecha_liquidaciones',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='legajo',
        ),
        migrations.AddField(
            model_name='ticket',
            name='agente_legajo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='devoluciones',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='concepto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usuario',
            field=models.CharField(default='enzofuentes', max_length=100),
        ),
    ]
